drop table if exists customer CASCADE;
create table customer
(
    id            bigint generated by default as identity,
    customer_name varchar(10),
    age           integer,
    phone_number  varchar(20),
    primary key (id)
);


